version: '3.8'

services:
  pihole:
    image: pihole/pihole
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
      - 443:443/tcp
    networks:
      - default
    volumes:
      - pihole:/etc/pihole/
      - dnsmasq:/etc/dnsmasq.d/
    env_file: 
      - ./config.env
      - ./secrets.env

networks:
  default:
    driver: overlay

volumes:
  pihole:
  dnsmasq: