version: "3.8"

services:
  nextcloud:
    image: nextcloud
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - default
    volumes:
      - nextcloud:/var/www/html
    env_file:
      - ./secrets.env
    secrets:
      - nextcloud-stack

  db:
    image: postgres:12
    restart: always
    networks:
      - default
    volumes:
      - db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_HOST=db
    env_file:
      - ./secrets.env
    secrets:
    - nextcloud-stack

networks:
  default:
    driver: overlay

volumes:
  nextcloud:
  db: