version: "3.8"

services:
  nextcloud:
    image: nextcloud
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - default
    volumes:
      - nextcloud:/var/www/html
    environment: 
      - POSTGRES_HOST=db
    env_file:
      - ./secrets.env

  db:
    image: postgres:12
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - default
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./secrets.env

networks:
  default:
    driver: overlay

volumes:
  nextcloud:
  db: